# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2523d51dce1b8f573a34bbe7f8583172"
name = "Store-Credit-Reminder"
application_url = "https://credit.apps.tmgindustrial.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_customers,read_store_credit_accounts"

[auth]
redirect_urls = [ "https://credit.apps.tmgindustrial.com/auth/callback" ]
